project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"
    - "*.Rmd"
    - "!*.md"
  resources: 
  - "assets"
  - "ads.txt"
  #post-render: 
    #- "cp -rnv static/. _site" # source: https://github.com/quarto-dev/quarto-cli/discussions/4162#discussioncomment-4831352

website:
  title: "Yuxin Fu"
  site-url: https://rubuky.com
  favicon: "assets/dianyi/tropico.ico"
  description: "Political Economy/Causal Inference/Game Theory."
#  google-analytics: "G-J9JHQ6RJV3"
  comments: 
    giscus:
      repo: kv9898/website
      repo-id: R_kgDOMx274g
      category: general
      category-id: DIC_kwDOMx274s4Ciftj
      mapping: title
      reactions-enabled: true
      theme:
        light: light
        dark: dark_dimmed
      language: en
  navbar:
    logo: assets/dianyi/tropico.png
    tools:
    #- icon: github
    #  href: https://www.github.com/kv9898/website
    right:
      - text: About
        aria-label: "About Me"
        href: about/index.qmd
      - text: Blog
        aria-label: "My Blogs"
        href: blog/index.qmd
      #- text: Talks
      #  aria-label: "Invited Talks"
      #  href: talk/index.qmd  
      - text: Papers
        aria-label: "Papers"
        href: papers/index.qmd
      #- text: Tools
      #  aria-label: "Tools"
      #  href: tools/index.qmd
      - text: CV
        aria-label: "CV"
        href: cv/CV_Yuxin.pdf
      #- text: Projects
      #  aria-label: "Project Portfolio"
      #  href: project/index.qmd

  #repo-url: https://github.com/kv9898/website
  #repo-actions: [source, issue]

  page-footer:  
    left: >-
     &#169; 2024 Yuxin Fu  &#8729; Made with [Quarto](https://quarto.org).<br>Based on [Silvia Canelón's](https://silviacanelon.com/) template.<br><a href="https://www.flaticon.com/free-icons/cabbage" title="cabbage icons">Cabbage icons from Park Jisun - Flaticon</a>.
    center: |
      <a class="link-dark me-1" href="https://github.com/Bim382" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link-dark me-1" href="https://www.youtube.com/@bim382" title="youtube" target="_blank" rel="noopener">{{< fa brands youtube >}}</a>
      <a class="link-dark me-1" href="https://www.instagram.com/yfu382" title="instagram" target="_blank" rel="noopener">{{< fa brands instagram >}}</a>
      <a class="link-dark me-1" href="https://orcid.org/0009-0003-0905-0207" title="orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>  
      <a class="link-dark me-1" href="https://space.bilibili.com/21636878" title="Bilibili" target="_blank" rel="noopener">{{< fa brands bilibili >}}</a>

    right: 
      - text: License
        aria-label: "License Details"
        href: license.qmd
      - text: Contact
        aria-label: "Contact Form"
        href: "contact.qmd"
      

execute: 
  freeze: auto

format: 
  html:
    theme:
      light:
        - cosmo
        - assets/dianyi/dianyi-theme-light.scss
        - assets/dianyi/colors-light.scss
      #dark:
      #  - cosmo
      #  - assets/dianyi/dianyi-theme-dark.scss
      #  - assets/dianyi/colors-dark.scss
    highlight-style: a11y
    # include-in-header: 
      #- text: |
      #    <script id="Cookiebot" src="https://consent.cookiebot.com/uc.js" data-cbid="ce728f8a-dbdd-41e4-a940-81ab3c45bfe1" type="text/javascript" async></script>
      #    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8745077864238831"crossorigin="anonymous"></script>
      #    <meta name="google-adsense-account" content="ca-pub-8745077864238831">
    # include-before-body: 
    #   - assets/dianyi/load_theme.js